language: d

matrix:
  include:
    - d: dmd-beta
    - d: dmd-2.084.1
      env: [COVERAGE=true]
    - d: dmd-2.076.1
    - d: ldc-1.14.0
    - d: ldc-1.13.0
    - d: ldc-1.12.0
    - d: ldc-1.11.0
    - d: ldc-1.10.0
    - d: ldc-1.9.0
    - d: ldc-1.8.0
    - d: ldc-1.7.0
    - d: ldc-1.6.0
    - d: dmd-2.083.1
    - d: dmd-2.082.1
    - d: dmd-2.081.2
    - d: dmd-2.080.1
    - d: dmd-2.079.1
    - d: dmd-2.078.3
    - d: dmd-2.077.1

sudo: false

script: ./travis.sh
