language: d

os:
    - linux
    - osx

d:
  # order: latest DMD, oldest DMD, LDC/GDC, remaining DMD versions
  # this way the overall test time gets cut down (GDC/LDC are a lot
  # slower tham DMD, so they should be started early), while still
  # catching most DMD version related build failures early
  - dmd-2.082.0
  - dmd-2.076.1
  - ldc-1.11.0
  - ldc-1.10.0
  - ldc-1.9.0
  - ldc-1.8.0
  - ldc-1.7.0
  - ldc-1.6.0
  - dmd-beta
  - dmd-2.081.2
  - dmd-2.080.1
  - dmd-2.079.0
  - dmd-2.078.3
  - dmd-2.077.1

env:
    - CONFIG=select
    - CONFIG=epoll
    - CONFIG=kqueue
    - CONFIG=libasync

matrix:
  allow_failures:
    - d: dmd-beta
  exclude:
    - env: CONFIG=libasync
    - os: osx
      env: CONFIG=epoll
    - os: linux
      env: CONFIG=kqueue
    - os: osx
      d: dmd-beta

script: ./travis-ci.sh

sudo: false
